version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  auth-api:
    container_name: auth-api
    build:
      context: auth-api
      dockerfile: Dockerfile
    networks:
      - backend
    ports:
      - 3000:3000
    env_file: .env
    restart: always

  user-api:
    container_name: user-api
    build:
      context: ./
      dockerfile: ./user-api/Dockerfile
    networks:
      - backend
    ports:
      - 3003:3000
    env_file: .env
    depends_on:
      - "postgres"
    volumes:
      - ./upload:/app/dist/upload
    restart: always

  nginx:
    container_name: nginx
    image: nginx:1.22.1-alpine
    networks:
      - backend
      - frontend
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "chat-api"
      - "game-api"
      - "auth-api"
      - "user-api"
    restart: always

  front-end:
    container_name: front-end
    build:
      context: front
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 3002:80
    env_file: .env
    restart: always

  chat-api:
    container_name: chat-api
    build:
      context: ./
      dockerfile: ./chat-api/Dockerfile
    networks:
      - backend
    ports:
      - 3004:3000
    depends_on:
      - "postgres"
    env_file: .env
    restart: always

  game-api:
    container_name: game-api
    build:
      context: ./
      dockerfile: ./game-api/Dockerfile
    networks:
      - backend
    ports:
      - 3005:3000
    depends_on:
      - "postgres"
    env_file: .env
    restart: always

volumes:
  postgres-data:
    name: postgres-data

networks:
  backend:
    name: backend_net
    driver: bridge

  frontend:
    name: frontend_net
    driver: bridge
