/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendance API
 * ft_transcendance API
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AvatarOutput
 */
export interface AvatarOutput {
    /**
     * 
     * @type {number}
     * @memberof AvatarOutput
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof AvatarOutput
     */
    path: string;
}

/**
 * Check if a given object implements the AvatarOutput interface.
 */
export function instanceOfAvatarOutput(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "path" in value;

    return isInstance;
}

export function AvatarOutputFromJSON(json: any): AvatarOutput {
    return AvatarOutputFromJSONTyped(json, false);
}

export function AvatarOutputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AvatarOutput {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'path': json['path'],
    };
}

export function AvatarOutputToJSON(value?: AvatarOutput | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'path': value.path,
    };
}

