/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendance API
 * ft_transcendance API
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OauthToken
 */
export interface OauthToken {
    /**
     * 
     * @type {string}
     * @memberof OauthToken
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof OauthToken
     */
    tokenType: string;
    /**
     * 
     * @type {number}
     * @memberof OauthToken
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof OauthToken
     */
    refreshToken: string;
    /**
     * 
     * @type {string}
     * @memberof OauthToken
     */
    scope: string;
    /**
     * 
     * @type {number}
     * @memberof OauthToken
     */
    createdAt: number;
}

/**
 * Check if a given object implements the OauthToken interface.
 */
export function instanceOfOauthToken(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accessToken" in value;
    isInstance = isInstance && "tokenType" in value;
    isInstance = isInstance && "expiresIn" in value;
    isInstance = isInstance && "refreshToken" in value;
    isInstance = isInstance && "scope" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function OauthTokenFromJSON(json: any): OauthToken {
    return OauthTokenFromJSONTyped(json, false);
}

export function OauthTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): OauthToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'],
        'expiresIn': json['expires_in'],
        'refreshToken': json['refresh_token'],
        'scope': json['scope'],
        'createdAt': json['created_at'],
    };
}

export function OauthTokenToJSON(value?: OauthToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'access_token': value.accessToken,
        'token_type': value.tokenType,
        'expires_in': value.expiresIn,
        'refresh_token': value.refreshToken,
        'scope': value.scope,
        'created_at': value.createdAt,
    };
}

