/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendance API
 * ft_transcendance API
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPartialUpdateRequest
 */
export interface UserPartialUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdateRequest
     */
    username?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserPartialUpdateRequest
     */
    twoFa?: boolean;
}

/**
 * Check if a given object implements the UserPartialUpdateRequest interface.
 */
export function instanceOfUserPartialUpdateRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserPartialUpdateRequestFromJSON(json: any): UserPartialUpdateRequest {
    return UserPartialUpdateRequestFromJSONTyped(json, false);
}

export function UserPartialUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPartialUpdateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'twoFa': !exists(json, 'twoFa') ? undefined : json['twoFa'],
    };
}

export function UserPartialUpdateRequestToJSON(value?: UserPartialUpdateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'twoFa': value.twoFa,
    };
}

