/* tslint:disable */
/* eslint-disable */
/**
 * ft_transcendance API
 * ft_transcendance API
 *
 * The version of the OpenAPI document: 1.0.11
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorOutput,
  MatchOutput,
} from '../models';
import {
    ErrorOutputFromJSON,
    ErrorOutputToJSON,
    MatchOutputFromJSON,
    MatchOutputToJSON,
} from '../models';

export interface GetMatchHistoryRequest {
    onset?: number;
    length?: number;
}

/**
 * 
 */
export class MatchsApi extends runtime.BaseAPI {

    /**
     * Get the match history for the connected user
     */
    async getMatchHistoryRaw(requestParameters: GetMatchHistoryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MatchOutput>>> {
        const queryParameters: any = {};

        if (requestParameters.onset !== undefined) {
            queryParameters['onset'] = requestParameters.onset;
        }

        if (requestParameters.length !== undefined) {
            queryParameters['length'] = requestParameters.length;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/users/me/match_history`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MatchOutputFromJSON));
    }

    /**
     * Get the match history for the connected user
     */
    async getMatchHistory(requestParameters: GetMatchHistoryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MatchOutput>> {
        const response = await this.getMatchHistoryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
